//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CarId { get; set; }
        public string CarName { get; set; }
        public string CarModel { get; set; }
        public string CarNumber { get; set; }
        public string VIN { get; set; }
        public string CarType { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
