//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Services Services { get; set; }
    }
}
