//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auta()
        {
            this.RezerwacjaAuto = new HashSet<RezerwacjaAuto>();
            this.RezerwacjaAuto1 = new HashSet<RezerwacjaAuto>();
        }
    
        public int AutoId { get; set; }
        public string NazwaAuta { get; set; }
        public string ModelAuta { get; set; }
        public string NumerRejestracyjny { get; set; }
        public string VIN { get; set; }
        public string TypAuta { get; set; }
        public Nullable<int> KlientId { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjaAuto> RezerwacjaAuto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjaAuto> RezerwacjaAuto1 { get; set; }
    }
}
