//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CzesciZamienne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CzesciZamienne()
        {
            this.RaportCzesc = new HashSet<RaportCzesc>();
            this.RaportCzesc1 = new HashSet<RaportCzesc>();
        }
    
        public int CzescId { get; set; }
        public string NazwaCzesci { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<decimal> KosztSztuka { get; set; }
        public string TypAuta { get; set; }
        public string TypFelgi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaportCzesc> RaportCzesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaportCzesc> RaportCzesc1 { get; set; }
    }
}
