//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaportUslugi
    {
        public int RaportUslugiId { get; set; }
        public Nullable<int> RaportId { get; set; }
        public Nullable<int> UslugaId { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Raport Raport { get; set; }
        public virtual Uslugi Uslugi { get; set; }
        public virtual Uslugi Uslugi1 { get; set; }
    }
}
