//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaportCzesc
    {
        public int RaportCzescId { get; set; }
        public Nullable<int> RaportId { get; set; }
        public Nullable<int> CzescId { get; set; }
        public Nullable<int> IloscUzytejCzesci { get; set; }
    
        public virtual CzesciZamienne CzesciZamienne { get; set; }
        public virtual CzesciZamienne CzesciZamienne1 { get; set; }
        public virtual Raport Raport { get; set; }
    }
}
