//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezerwacjaAuto
    {
        public int RezerwacjaAutoId { get; set; }
        public Nullable<int> RezerwacjeId { get; set; }
        public Nullable<int> AutoId { get; set; }
    
        public virtual Auta Auta { get; set; }
        public virtual Auta Auta1 { get; set; }
        public virtual Rezerwacje Rezerwacje { get; set; }
    }
}
