//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacje()
        {
            this.Raport = new HashSet<Raport>();
            this.RezerwacjaAuto = new HashSet<RezerwacjaAuto>();
            this.RezerwacjaUsluga = new HashSet<RezerwacjaUsluga>();
        }
    
        public int RezerwacjeId { get; set; }
        public Nullable<int> KlientId { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raport> Raport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjaAuto> RezerwacjaAuto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjaUsluga> RezerwacjaUsluga { get; set; }
    }
}
