//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTiresService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uslugi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uslugi()
        {
            this.RaportUslugi = new HashSet<RaportUslugi>();
            this.RaportUslugi1 = new HashSet<RaportUslugi>();
            this.RezerwacjaUsluga = new HashSet<RezerwacjaUsluga>();
            this.RezerwacjaUsluga1 = new HashSet<RezerwacjaUsluga>();
        }
    
        public int UslugaId { get; set; }
        public string NazwaUslugi { get; set; }
        public Nullable<decimal> Koszt { get; set; }
        public Nullable<System.TimeSpan> CzasTrwania { get; set; }
        public string TypAuta { get; set; }
        public string TypFelgi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaportUslugi> RaportUslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaportUslugi> RaportUslugi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjaUsluga> RezerwacjaUsluga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjaUsluga> RezerwacjaUsluga1 { get; set; }
    }
}
